public class SalesforceDeveloper {
    public void myFirstCode(){
        string myFavoriteCity = 'Dar es Salaam';
        string myFavoriteMovie = ' Interstellar';
        string myFavoriteSeason = ' Spring ';

        system.debug('My favorite city is ' + myFavoriteCity);
        system.debug('My favorite movie is ' + myFavoriteMovie);
        system.debug('My favorite season is ' + myFavoriteSeason);
    }
    public void myFavorites(){
        string myCity = 'Seattle';
        integer myFavoriteNumber = 5;
        system.debug('My favorite number is ' + myFavoriteNumber + ' and ' + 'I live in ' + myCity );
    }
}