ListDemo.iterateList();
ListDemo.allCats();

ListDemo.candidateList();
ListDemo.randomIntegerList();
ListDemo.randomIntegerList2();
//ListDemo.candidateListNew(6);
String c2 = ListDemo.candidateListnew(2);
System.debug('c2 is: ' + c2);
String c3 = ListDemo.candidateListnew(3);
System.debug('c3 is: ' + c3);

String c3 = ListDemo.candidateListSize(3);
System.debug('c3 is: ' + c3);
String c6= ListDemo.candidateListSize(6);
System.debug('c6 is: ' + c6);


