String m2 = MapDemo.retrieveMonth(2);
System.debug('2nd Month ===>' + m2);
String m6 = MapDemo.retrieveMonth(6);
System.debug('6th Month ===>' + m6);
String m13 = MapDemo.retrieveMonth(13);
System.debug('13st Month ===>' + m13);

String m2 = MapDemo.retrieveMonth2(2);
System.debug('2nd Month ===>' + m2);
String m6 = MapDemo.retrieveMonth2(6);
System.debug('6th Month ===>' + m6);
String m13 = MapDemo.retrieveMonth2(13);
System.debug('13st Month ===>' + m13);
